FROM debian:buster-slim

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		ca-certificates \
		wget \
# add "apt-transport-https" for images whose "/etc/apt/sources.list" uses "https"
		apt-transport-https \
# redhat-based images!
		rpm \
		yum-utils \
	; \
	rm -rf /var/lib/apt/lists/*

COPY .local-scripts/*.sh /usr/local/bin/

CMD ["gather.sh"]
